### ISSUE TITLE
[PTR][Dungeon] Lost City of Tol'Vir Bosses - Issues found (list)

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1346]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Compiling into one list for ease of access 

1) General Husam -  Does not use "Hammer Fist".
Shockwave, Bad intentions & Mystic trap working perfectly
2) Lockmaw - No issues found, mechanics are working
3) High Prophet Barim - Repentance should knock back players when finished casting when phase 2 triggered.
Soul Fragments do spawn from Soul Sever but do not function correctly.  Should walk slowly towards the Harbringer of Darkness, and when touching it will heal the harbinger and increase size.  Soul Sever / Soul Fragments only spawn outside the "Realm of darkness" and are rendered useless

4) Siamat -  If wind tunnel is clicked by multiple players it bugs out and leaves someone stranded down on the floor,  not a huge issue but a slight pain.  player left on ground can click again to get into the boss area 

Minion of Siamat when deathgripped will fall through the floor and become unattackable 

Wailing winds should do nature damage every second for 6 seconds, and fling the player 3 times during the cast, it only "knocks them around" once and does no damage after the first hit 

player pets also fall through the floor at random intervals on 2nd phase -  e.g. shadowfiend from priest 

When Siamat is killed he also falls down into the floor 

**Database links:**
https://cata-twinhead.twinstar.cz/?npc=44577 - General Husam
https://cata-twinhead.twinstar.cz/?npc=43612 - High Prophet Barim
https://cata-twinhead.twinstar.cz/?npc=44819

**Comment by MrTide** [comment]
Confirmed the reports above 
they require attention

**Comment by Afgann** [comment]
fixed

**Comment by WhitemaneSylah** [comment]
Initiation: 
Oathsworn captains do not use earthquake ability



General Husam : Does not use traps 

Lockmaw :  Scent applies but small crocks do not target player afflicted with scent
Dust flail is killing pets in one shot

Phase 2 - Augh ; Should engage as soon as lockmaw dies.
Does not use smoke bomb at all.  WHirlwind causes him to move at 100% speed, he should move at 60%

Barim - Repentence ends too quickly
Phase 2 - Soul Sever works , But soul Fragments are not functioning correctly,  THey spawn with too much hp (50k ,should be 5k) and move at 100% speed, should move at 30% 
Sometimes soul fragments dont even spawn

Siamat:  pets can fall under textures on boss room

classes with gap closers (IE charge) constantly get "no path available" error

Siamat should start the fight invulnerable to damage but he can be attacked for 4-5 seconds 

Servant of Siamat - They should spawn once ever 45 seconds and should continue to spawn another two more in 45 second intervals OR spawn immediately if one dies.
Only 1 servent of Siamat gives a stack of Lightning charge,  this should be given by every servent when they reach 4% (meaning thte total amount of charges will be 3 by phase 2) 
<GM> Sylah — Today at 16:11
https://www.youtube.com/watch?v=2V7HYEsaCyc Retail video
[YouTube](https://www.youtube.com/)
[TotalBiscuit](https://www.youtube.com/channel/UCy1Ms_5qBTawC-k7PVjHXKQ)
[WoW Cataclysm Guide - Heroic Lost City of the Tol'vir](https://www.youtube.com/watch?v=2V7HYEsaCyc)
Image
Kinden — Today at 16:11
https://youtu.be/FBfPz1tF1nU Tank perspective

**Comment by WhitemaneSylah** [comment]
GaGa — Today at 21:12
General Husam : Does not use traps Missing traps names / traps timers (you can grab that often on wowwikki tactics section)
Lockmaw: Dust flail is killing pets in one shot they shouldn't target pets or they should deal less damage? please specify amount of avg. amount of damage.
Phase 2 - Augh ; Should engage as soon as lockmaw dies. What's the current behavior?  he doesn't engage at all?
Siamat:  pets can fall under textures on boss room Is there specific location of such behavior? or it happen regardless of position at the boss room.
Smite — Today at 21:21
#1 Mystic trap, they tend to spawn around every 10 sec
https://wowpedia.fandom.com/wiki/General_Husam
#2 avoidance is not working correctly for that spell, pets are usually trying to hit boss from behind so they take dmg from dust flail
#3 he just spawn and wait for being pulled( combat is dropping when it shouldn't, crocodile and augh are counting as one encounter)
#4 ghoul was falling in textures during whole encounter, position in room doesnt matter

**Comment by Hotandspicy322** [comment]
High Prophet Barim
 the spell Plague of Ages is gettin cast twice everytime it is done , and is cast that shortly after another that it has a 90%+ 
 (guessed the %) uptime in p1 and p3 
  it was needed to do 32044,2 HPS
  and that is far from possible solo healing in gear that one would have when the server is life
  in the end i used QA items to heal it so we could continue 
  in the screenshots you can see the numbers in the lower right corner
![WoWScrnShot_011623_194404](https://user-images.githubusercontent.com/122824463/212747398-caa28dd7-f6a7-457c-a0c1-6c6549d56cce.jpg)
![WoWScrnShot_011623_194410](https://user-images.githubusercontent.com/122824463/212747420-da81272c-b274-412c-a192-914f830e2947.jpg)

**Comment by WhitemaneSylah** [comment]
Augh
- no animation on Smoke Bomb attack, but the stun does apply correctly.

Siamat 
- Boss falls under the ground when he enters phase 2. charging him (tank PoV video) taps the player under the boss floor. 
- boss loot falls under the map on death, rendering loot unobtainable with GM interaction.

**Comment by Afgann** [comment]
fixed

**Comment by WhitemaneSylah** [comment]
General Husam

Bad Intentions - knocking up in place (instead of pinning targeted player to pillar/wall), not stunned (can still use instant cast spells in the air) [SCREENSHOT](https://imgur.com/a/0nOInhj)
High Prophet Barim

When the boss gets phased ( at 50% hp, Repentance ) his AOE around the boss called "Hallowed Ground" can miss players.
On that phase, Soul Fragments ( Pops on random players except tank, and runs to the Harbringer of Darkness ) Should be able to die on Fire (Blaze of the Heavens) that remains on the ground from the first phase, which is not happening now we tried it today a lot of times without success, it's the objective of [Kill It With Fire!](https://wowpedia.fandom.com/wiki/Kill_It_With_Fire!) players have to kite 3 Soul Fragments on Fire (Blaze of the Heavens) and they should die by that fire, so the achievement is not working.

**Comment by WhitemaneSylah** [comment]
Retest 28.01 
Siamat :

Servant of Siamat (GUID 104, entry 45296)  Spawning much faster now but still not correct.  Refer to below screenshot,  When the Servant dies ,  Theirs no new servant spawning for at least 5 seconds,  the trigger needs to be changed to spawn IMMEDIATELY if the servant dies OR 45 seconds after the 1st one spawns IF the current servant is not dead 
![image](https://user-images.githubusercontent.com/121137397/215274845-5c634678-7ce6-4d71-8254-4320c4f9b644.png)

Wind Tunnel below does not function correctly, when using it ,  character is ported in the air but not back onto boss platform
![image](https://user-images.githubusercontent.com/121137397/215274618-fba2a92a-3019-4393-9eda-ded400075446.png)

**Comment by Commander-Rug090** [comment]
Siamat, only fight to test Vortexes and boss staying on platform https://youtu.be/VcnvVR5qfjs

&

tol vir full run Tank PoV https://youtu.be/zIL9TEk7yc8

**Comment by UltraNix** [comment]
Fixed.

**Comment by Commander-Rug090** [comment]
Update: **High Prophet Barim:**
priests able to target and damage their shadowy apparitions.
