### ISSUE TITLE
[Mage] Living bomb

### ISSUE THREAD

**Issue by Dechuka** [gamefreedomgit/Maelstrom#1378]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Living bomb affects more than 3 targets which it should not:**

**cast living bomb on a target then spread it with fire blast (impact) you will see it affects all nearby targets (more than 3)):**

**living bomb is limited to 3 targets):**

**https://cata-twinhead.twinstar.cz/?spell=44457**

**Comment by Afgann** [comment]
fixed

**Comment by Dechuka** [comment]
After today's update, the issue is back, I guess it has to do with this report
https://github.com/gamefreedomgit/Maelstrom/issues/1551

**Comment by Afgann** [comment]
fixed

**Comment by Dechuka** [comment]
I tested it after the fix, still the same issue , the targets are unlimited

**Comment by Afgann** [comment]
fixed, i'll wait for feedback before closing this issue, let me know if it works after next update @Dechuka

**Comment by Dechuka** [comment]
right now it affects only 3 targets.
however, if there are more than 3 targets, the main target loses its living bomb and goes to another target.
it should not be like this, once it got spread, the main target keeps its living bomb, and 2 more targets suffers from it

**Comment by Afgann** [comment]
fixed
