### ISSUE TITLE
The Hinterlands Alliance Levelling Report

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1437]
1. [Razorbeak Friends](https://www.wowhead.com/quest=26546/razorbeak-friends)
- You can feed one [Trained Razorbeak](https://www.wowhead.com/npc=2657/trained-razorbeak) multiple times for quest credit, if you are fast enough using [the item](https://www.wowhead.com/item=58935/gryphon-chow) 2nd time. This should not be the case imo.

2. [Rhapsody Shindigger](https://www.wowhead.com/npc=5634/rhapsody-shindigger)
- This NPC have chat option as the teleport in Icecrown Citadel. Shouldn't be so, though it is funny.

3. If you try to enter Emerald Dram portal in Hinterladns you will get teleported to Ruins of Feathermoon in Feralas. Not sure if that is supposed to happen.

4. [Ongo'longo's Revenge](https://www.wowhead.com/quest=26515/ongolongos-revenge)
- The script of this quest is incomplete. [Ongo'longo](https://www.wowhead.com/npc=42815/ongolongo) will use the yell emotes properly when at low hp, Shackles will despawn, the [Vilebranch Handler](https://www.wowhead.com/npc=42843/vilebranch-handler) will spawn. However Ongo keeps the player in combat and nothing happens. Shortly after both Ongo'longo and the troll npc will despawn.
- Video: https://www.youtube.com/watch?v=BhU2t0OVoT4 2:10

5. [Venomous Secrets](https://www.wowhead.com/quest=26525/venomous-secrets)
- This quest is avaialble at the same time as [Summit of Fate](https://www.wowhead.com/quest=26517/summit-of-fate).
- It should be available only after completing Summit of Fate, together with Hunt the Keeper.
- Video: https://www.youtube.com/watch?v=K5Pvd0anE4w

6. [Morta'gya the Keeper](https://www.wowhead.com/npc=42877/mortagya-the-keeper#abilities) was nto using her abilities on me.

7. If you fly [Sharpbeak](https://www.wowhead.com/npc=51125/sharpbeak) (not sure about ID), he spawns /say belonging to [Inspector Tarem](https://www.wowhead.com/npc=23567/inspector-tarem).

8. [In Defense of Quel'Danil](https://www.wowhead.com/quest=27625/in-defense-of-queldanil)
- There is either not enough of [Deathstalker Invaders](https://www.wowhead.com/npc=43541/deathstalker-invader) or they do not respawn fast enough
- There are no [Higvale Swiftblades](https://www.wowhead.com/npc=43539/highvale-swiftblade) fighting the Invaders.
They should be spawned isntead of [Highvale Sentries](https://www.wowhead.com/npc=46478/highvale-sentry) during the quest being active, at least that is what wowhead comment says on Highvale Swiftblade page.
- Video: https://www.youtube.com/watch?v=wdHqFTRJKzY

9. [Rescue OOX-09/HL!](https://www.wowhead.com/quest=836/rescue-oox-09-hl)
- Pathing of the chicken is a bit faulty (wlats through tree, goes underground for a bit
- The animation of chicken starting jet engines and flying away is missing, it simply despawns on quest complete
- The player and chicken gets attacked twice by 6 [Marauding Owlbeasts](https://www.wowhead.com/npc=7808/marauding-owlbeast). It should be only 3 in each wave.
- Momentarily you need to escord the chicken to the beach but on post-wotlk videos it is not that far (unsure point), it ends after 1st wave of 3 owlkins.
- Videos: 2015 https://www.youtube.com/watch?v=SfBr4OWqrQ8; 2011 https://www.youtube.com/watch?v=H9_aIW0lF5I
- Someone more knowledgable needs to confirm as which path and what spawns are correct for Cata.

10. [Violet Tragan](https://www.wowhead.com/object=141853/violet-tragan)
- Visible on Herbalism map (Find Herbs).
- Although not clickable and not showing anything when hovered over, it still shimmers as lootable Q item.
- Violet Tragan, the item looted from the object was removed with Cata (source wowpedia), so the object should not shimmer and should not be visible on herbalism map (most likely).

**Comment by UltraNix** [comment]
Fixed.

**Comment by Griskon** [comment]
There is still a problem with this quests. If you accept the one where you have to defend and kill NPCs. The Questgiver disappears and you can't complete it.
