### ISSUE TITLE
[Quest][Event] Finishin' the Job

### ISSUE THREAD

**Issue by Loken-coolguy** [gamefreedomgit/Maelstrom#1540]
Video Reference: https://youtu.be/NpigGE251pY?list=PLOKWqvjv-eHa3opLF0qS8K9FSd8Nbzt67&t=637

There should be a bunch of dynamite and some animations going on as seen in the video. You press the Detonator, an explosion happens, and then the ceiling caves in. Currently, it appears like it has already been caved in before pressing the Detonator: 
![image](https://user-images.githubusercontent.com/67768754/210159600-3f548409-4f94-45c3-a1af-c79b61b0039f.png)

Pressing the Detonator finishes the quest currently and does nothing.

**Comment by UltraNix** [comment]
Fixed.

**Comment by Loken-coolguy** [comment]
This still isn't happening, it is still caved in before the detonation and Pressing the Detonator finishes the quest and does nothing else

**Comment by GmOkami** [comment]
Tested - valid
