### ISSUE TITLE
[Mage] Spreading Ignite with fire blast (impact)

### ISSUE THREAD

**Issue by Dechuka** [gamefreedomgit/Maelstrom#1551]
**Fire blast (impact) allows you spread the fire damage over time to nearby targets:**
https://cata-twinhead.twinstar.cz/?spell=12357

**cast single target fire spells to make the target suffers from ignite then spread  its  damage to nearby targets ( with impact), although it shows ignite debuff to all nearby targets, but they suffer 0 damage  **

How it should work: ignite that got spread should deal damage to all nearby targets

**Comment by Afgann** [comment]
fixed

**Comment by Dechuka** [comment]
just tested it, still not fixed,
it shows that nearby targets suffer from ignite (shows the debuff on the targets) , but no damage dealt to them

**Comment by Dechuka** [comment]
After the fix, it does spread now, however the damage is less than suppose to be, it should be the same from the main target
