### ISSUE TITLE
[Class: Paladin] Seal effects not applying on absorb effects

### ISSUE THREAD

**Issue by WhitemaneSylah** [gamefreedomgit/Maelstrom#1566]
All paladin seals are not applying through absorb effects,  This includes ret paladins talented Seals of Command (cleave from the talent, The 7% portion is working fine)

Seal of Righteousness - Not applying extra damage when absorbed
Seal of Insight - not giving back mana/hp when damage is absorbed
Seal of Justice - Not applying slow when absorbed
Seal of Truth - Not applying Censure debuff when attack is absorbed

This was tested on Priests Power World: Shield,  Paladins Holy mastery Illumination & Warlocks sacrifice 

https://cata-twinhead.twinstar.cz/?spell=31803 - Censure
https://cata-twinhead.twinstar.cz/?spell=99092 - Flames of the Faithful
https://cata-twinhead.twinstar.cz/?spell=76672 - Hand of Light
https://cata-twinhead.twinstar.cz/?spell=20154 - Seal of Righteousness
https://cata-twinhead.twinstar.cz/?spell=85126 - Seals of Command
https://cata-twinhead.twinstar.cz/?spell=20164 - Seal of Justice

**Comment by Afgann** [comment]
fixed

**Comment by WhitemaneSylah** [comment]
Flames of the Faithful and Hand of Light still not proccing on Absorb
