### ISSUE TITLE
[Quest][Cata] Weapons of Mass Dysfunction 

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1598]
**Description:**
This quest can be found in orgrimmar

**How to reproduce:**
As you can see on the image after completing the task chief engineer spawns again and in long term it will cause issues, you can't even kick some of them including other engineers next to other demolishers
![image](https://user-images.githubusercontent.com/36106057/210417998-a366980f-1e3e-4133-ab43-24ae5a4258ee.png)
![image](https://user-images.githubusercontent.com/36106057/210418267-f7578ed2-04a0-457b-a116-2d294f189aa7.png)

**How it should work:**
Like the video below 
https://www.youtube.com/watch?v=7DqaFwa9Z_8
**Database links:**
https://cata-twinhead.twinstar.cz/?quest=26294

**Comment by Afgann** [comment]
fixed

**Comment by Esmeralda-CM** [comment]
This is still broken, we received a ticket about it today 

Player stated they were clicking on the demos and nothing was happening

**Comment by hAi777** [comment]
This quest got broken again. Clicking on demo does nothing.
