### ISSUE TITLE
[Quest][Cata] The Bears Up There quest locks the quest line - questID 25462

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#1897]
**How to reproduce:**  The Bears Up There quest is not scripted properly once you reach top of the tree your UI to throw the bears are gone you can't do anything, you can't leave vehicle at any point, and once you click on the ladder
if you dont do this quest rest of the quests wont open up so we need to fix this

**How it should work:**
It should work like this video : https://www.youtube.com/watch?v=W_xfH6i0h2I

**Comment by GMHiki** [comment]
Yep, tested myself as well and this is exactly what happens. You can grab the bears and move up the tree, but once at the top the Vehicle UI is removed and you cannot throw the bear onto the trampoline. You are unable to dismount tree, etc.

**Comment by Greywolf59** [comment]
You can exit the game and reopen it to get down from the tree. Otherwise yes, can confirm. Also there is lot of bunnies called "Climbing Tree" instead of ladders.

**Comment by MrTide** [comment]
Update:
Sadly i couldnt do this quest due phasing issues i can't even see the quest giver, i had no other quest, even added the quest manually and still can't see anything (i have done all the other quests in this zone on this character (i was at phase 2 relog didnt change it)
i brought a secondary character completed the previous quest to that i could see it, it might be a good idea to fix the phasing issues so players can do it even if their phasing is changed because of doing other quests (second character was at phase 1)
![image](https://user-images.githubusercontent.com/36106057/221959855-ce3e4363-3d22-4ca8-9dc8-07da41c46d47.png)
after using gm on i could use the tree and ladders to climb up and down but you can only use one bear others wont work after getting one,

**Comment by Greywolf59** [comment]
Interesting. I had no issue doing it earlier today with character who already done all the quests around here and this was the only one left in this part (and Returnnto Aviana whoch did get fixed at same update)

**Comment by Sattva-108** [comment]
It is indeed, not well scripted. Can pickup only one bear, throw him and then you can't pickup bears anymore. Only if you climb all the way to the bottom and re-use the ladder.

**Comment by UltraNix** [comment]
Fixed.

**Comment by MrTide** [comment]
one of the issues still exist reopening the issue
![image](https://user-images.githubusercontent.com/36106057/224555306-66514226-bff7-4f1d-a3e8-258fc69d6e3e.png)
