### ISSUE TITLE
[Quest] Sandsorrow Watch - does not open follow-ups

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1939]
Quest: [Sandsorrow Watch](https://www.wowhead.com/quest=25091/sandsorrow-watch)

Issue: Handing in the Sandsorrow Watch does not open the next quest, [Blood to Thrive](https://www.wowhead.com/quest=25021/blood-to-thrive).

**Comment by Afgann** [comment]
fixed

**Comment by ootxc** [comment]
Still does not work. After handing in the Sandsorrow Watch quest, Mazoga does not offer any quests.

**Comment by ootxc** [comment]
Still does not work. After handing in the Sandsorrow Watch quest, Mazoga does not offer any quests.
