### ISSUE TITLE
[Quest] [Important] Dousing the Flames of Protection - missing

### ISSUE THREAD

**Issue by Greywolf59** [gamefreedomgit/Maelstrom#1968]
Quest: [Dousing the Flames of Protection](https://www.wowhead.com/quest=28126/dousing-the-flames-of-protection)

Issue:
After the player hands in [Purity From Corruption](https://www.wowhead.com/quest=28119/purity-from-corruption) this quest should be offered to him as follow up.
The quest is not offered and can't be acquired by any other means (except commands). This leads to Felwood Questline being stuck in about one third of the progress already.

Putting Felwood Bug report on hold until this gets fixed as I can't acquire almost any other further quests.

**Comment by UltraNix** [comment]
Fixed.

**Comment by meggynka** [comment]
It is not fixed !!! Quest is still missing for me and I cannot continue !! Please fix it.
