### ISSUE TITLE
[Profession Scrolls] Scroll of "Profession" Virtuosity 

### ISSUE THREAD

**Issue by MrTide** [gamefreedomgit/Maelstrom#2074]
**How to reproduce:** looks like using some of the scrolls of "profession" virtuosity causes them to sit on top of eachother and bug out.
these to be exact
![image](https://user-images.githubusercontent.com/36106057/216081511-086e2752-bbcf-40a6-bf4d-02b0060c896f.png)
![image](https://user-images.githubusercontent.com/36106057/216081545-6f03fbab-ec7a-4eda-8201-61adbfeb5366.png)

i have learned two but both are on top of each other
relog wont fix it
it doesnt happen everytime with all of them but with some it does for example alchemy and tailoring.
(for future reference just incase if you wanna include these in store)
![image](https://user-images.githubusercontent.com/36106057/216079092-a81d258c-f9a2-43d3-ba22-7fba68e80ca5.png)
i had to unlearn one to see otherone 
![image](https://user-images.githubusercontent.com/36106057/216079214-e066670d-68d8-44c6-910a-433da61417fc.png)

there are also some weird interactions with a few of them like
engineering and enchanting 
i unlearned enchanting and engineering shows up like this
![image](https://user-images.githubusercontent.com/36106057/216080663-84c6d2a1-67e0-4791-80d0-3829ebbf92e3.png)

i tried to learn engineering first then skinning and it happened again they were on top of eachother again
so order of how you learn them also causes this bug
![image](https://user-images.githubusercontent.com/36106057/216081114-f42ffd4a-8922-4499-a612-a4d6b6c6a113.png)
after unlearning engineering
![image](https://user-images.githubusercontent.com/36106057/216081181-6a1c56f4-dfac-4e4c-857c-69f176631e0f.png)

**How it should work:** they should not sit on top of eachother

**Comment by UltraNix** [comment]
Fixed.

**Comment by MrTide** [comment]
Still happening
just learned engineering and tailoring after
both were on first slot.

**Comment by Esmeralda-CM** [comment]
Seems to be a UI bug, can be "fixed" on the player side by already knowing one profession via class trainer

**Comment by MrTide** [comment]
> 

i am not sure what the cause is but happens everytime i just learned eng then tailor and it happened 
both through scroll

**Comment by Esmeralda-CM** [comment]
Seems to be only happening with the Engi scroll from what I can tell. 

- Engi + skinning bugged 
- Engi + Jewel bugged
- engi + Enchant WORKS
- engi + tailor bugged
- Engi + Alch causes me to have two Engi 
![image](https://user-images.githubusercontent.com/123559920/216794227-4ab8c04d-db1b-4110-92b9-0d319dde1f96.png)
![Screenshot 2023-02-04 184447](https://user-images.githubusercontent.com/123559920/216794230-3265097c-0b0a-4b01-8c95-7e32d2a8142c.png)

**Comment by MrTide** [comment]
player also sent this to us
![image](https://user-images.githubusercontent.com/36106057/216795328-f36aff65-73ec-4a03-aff1-63aec734e3e9.png)
