### ISSUE TITLE
[Spell] Scourge Strike shadow partition not scaling with magic damage taken debuff

### ISSUE THREAD

**Issue by testdk123** [gamefreedomgit/Maelstrom#2250]
**Description:**
The shadow portion of Scourge Strike isn't benefitting from the 8% magic damage taken debuff. It's really easy to see with Unholy DK's Ebon Plaguebringer debuff.

**How to reproduce:**
1. Cast Scourge Strike on a target with magic damage taken debuff applied.
2. Notice the lack of damage.

**How it should work:**
Should benefit from the 8% magic damage taken debuff.

Proof:

https://youtu.be/Tf1LiwVwfTE?t=932
10080 from the physical portion
**10531** from the shadow portion
Shadow portion should be phys portion * 0.54 (3 diseases multiplier) * 1.3 (glyph) * mastery
At 1:50 in the video you can see he has 15.12 mastery, so 37.8% increased shadow damage.
10080 x 0.54 x 1.3 x 1.378 = 9751
However if you include the 8% magic damage taken debuff: 
9571x1.08 = **10531**

Another example at 15:50
7717 from the physical portion
**8062** from the shadow portion

7717x0.54x1.3x1.378 = 7465
**7465x1.08 = 8062**

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=55090

**Comment by MullichWhitemane** [comment]
Confirmed:
![scourge strike](https://user-images.githubusercontent.com/121984461/221434300-5c28eccd-03ac-43ef-92e3-01b9bfc9fe37.PNG)
7198 (phys damage dealt) * 0.54 (3 diseases) * 1.39 (mastery) = 5403

**Comment by UltraNix** [comment]
Fixed.

**Comment by testdk123** [comment]
Unfortunately not really fixed. It works properly when your Ebon Plaguebringer is the only 8% damage taken debuff in the raid, but as soon as it's overwritten (be it by Curse of the Elements, Earth and Moon, Assa rogue's poison or Surv hunter wind serpent pet) your Scourge Strike will not benefit from the intended 8% magic damage taken debuff.

**Comment by UltraNix** [comment]
@testdk123 Make a new report about Ebon Plague not stacking with those effects.

**Comment by testdk123** [comment]
> @testdk123 Make a new report about Ebon Plague not stacking with those effects.

My details is showing Ebon Plaguebringer with 100% uptime, which makes sense taking into account my disease damage as well (they're benefitting from the 30% damage multiplier). 
Think the issue is that Scourge Strike isn't benefitting from the other 8% magic damage taken debuffs. Whichever 8% magic damage taken debuff is active, Scourge Strike should benefit from it.

**Comment by testdk123** [comment]
Then the spell script might need some hackfix? I understand the fixed damage flag to prevent double dipping, but it's very clear that the damage should actually benefit from the 8% magic damage taken debuff somehow.


Here's another example in a raid, again from Preach but on a 4.3 video:
Character stats:
![preach1](https://user-images.githubusercontent.com/126105309/228908798-1f774ded-4263-4cd5-a8d0-2b7a132f3d3f.png)
11.8 Mastery = 29.5% shadow damage. 
![preach2](https://user-images.githubusercontent.com/126105309/228908820-04e1a355-9d05-4503-a9c8-39efda0132d3.png)
Physical Portion: 18118
Shadow Portion: 19569

19930 * 0.54 * 1.3 * 1.295 = 18118
18118 * 1.08 = 19567
![preach3](https://user-images.githubusercontent.com/126105309/228909608-78dee43d-96aa-4736-bae5-3a277ec377ab.png)
Physical Portion: 16797
Shadow Portion: 16493

16797 * 0.54 * 1.3 * 1.295 = 15270
15270 * 1.08 = 16492

**Comment by testdk123** [comment]
> The damage of that spell is based on physical damage part, which already has taken these (% damage taken) auras into consideration and would make sense to not including them again, in the shadow part.

Also, just to make this clear, the physical portion of Scourge Strike does NOT benefit already from the magic damage taken debuff. There's no double dipping in this instance. 
I'd assume this is applied because the increased damage comes from a debuff on the target, rather than a buff on the player? Which is why it doesn't benefit from something like 3% increased damage from ret.

**Comment by UltraNix** [comment]
I will remove that attr and we'll see what happens :)

**Comment by UltraNix** [comment]
Fixed.
