### ISSUE TITLE
[Quest][Hyjal] Vision of Ysera - Hyjal Ancients Questline - Quest: The Last Living Lorkeeper

### ISSUE THREAD

**Issue by Torpis** [gamefreedomgit/Maelstrom#2262]
Description: When going through the Hyjal questline I finished An Ancient Awakens and saw the beam of green light that occurs when Vision of Ysera spawns, but the NPC did not spawn with the green light. I was unable to pickup the follow-up quest called "The Last Living Lorekeeper".

How to reproduce: Complete the Hyjal questline to the quest "An Ancient Awakens" then talk to Arch Druid Hamuul Runetotem and turn in the quest. A green beam of light will spawn.

How it should work: The green beam of light should also have an NPC named Vision of Ysera spawn as well to give the follow-up quest "The Last Living Lorekeeper". See the following video: https://youtu.be/Sc_KN9hrnrc?t=401

**Comment by Greywolf59** [comment]
I have mentioned this in Hyjal summary report. If it is at Malorne's Shrine or how is it called, she falls under the podium. Player can always go back to Nordrassil, to Ysera herself to pick up the quests offered by her visions.

**Comment by Greywolf59** [comment]
Yesterday she did offer it to me. Did the player in question finish Aviana branch already? Might play a role. Both need to be done to get The Last Living Lorekeeper afaik.

**Comment by UltraNixx** [comment]
Same -tested and quest is offered to me after completing Return to Aviana.

**Comment by Afgann** [comment]
fixed

**Comment by Greywolf59** [comment]
Not fixed properly. Now Imagie of Ysera does not spawn at all and palyer has to guess that he is supposed to return to Ysera proper.
Also upon logging out and logging back in in the zone Sanctuary of Malorne, player gets thrown into "Regrowth" phase as in other zones and has to leave and return, so also in this zone there is some strange phasing/layering present as mentioned in other recent github posts of mine.
