### ISSUE TITLE
[Quest] Blood in the Highlands Missing

### ISSUE THREAD

**Issue by Docpally** [gamefreedomgit/Maelstrom#2463]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

Description:
Blood in the Highlands quest (start of Crucible of Carnage quest chain) is missing.

**How to reproduce:**
No quest available

**How it should work:**
NPC [Harkkan] should have quest

**Database links:**
https://www.wowhead.com/quest=28038/blood-in-the-highlands
https://cata-twinhead.twinstar.cz/?quest=28038

**Comment by UltraNix** [comment]
Fixed.

**Comment by Docpally** [comment]
Still can't see this quest.
![image](https://user-images.githubusercontent.com/47340366/230373454-3f2397d2-c2c9-4990-9010-5d9bd6ba8557.png)

**Comment by UltraNix** [comment]
Have you done https://www.wowhead.com/quest=28123/the-demon-chain?

**Comment by Docpally** [comment]
No, havent completed 'The Demon Chain'(28123), because I can't do the quest before it 'How to Maim Your Dragon'(28043). I have completed the one before 'How to Maim Your Dragon'(28043), which is 'Bait and Throttle'(28041). So the Storyline should be:
1. 'Bait and Throttle'(28041)
2. 'How to Maim Your Dragon'(28043)
3.'The Demon Chain'(28123)

**Comment by UltraNix** [comment]
https://wowpedia.fandom.com/wiki/Blood_in_the_Highlands
According to this site `Blood in the Highlands` is a side quest after completing `[The Demon Chain](https://wowpedia.fandom.com/wiki/The_Demon_Chain_(quest))`

**Comment by Docpally** [comment]
> https://wowpedia.fandom.com/wiki/Blood_in_the_Highlands
> According to this site `Blood in the Highlands` is a side quest after completing `[The Demon Chain](https://wowpedia.fandom.com/wiki/The_Demon_Chain_(quest))`

Thats probably correct, but I can't complete The Demon Chain either. When I complete the quest 'Bait and Throttle' (its a repeatable quest), the next quest in the storyline, 'How to Maim Your Dragon'(28043), isn't there, so I can't complete it to then do 'The Demon Chain'(28123) and then `Blood in the Highlands`
