### ISSUE TITLE
Ammunae - [Halls of Origination]

### ISSUE THREAD

**Issue by Sketish** [gamefreedomgit/Maelstrom#2750]
Description:
Ammunae energy bar is not working at all.
He should get enemy from this ability
![image](https://user-images.githubusercontent.com/122209088/229147960-2023f151-de53-4d25-95fb-80aaa4df1b96.png)

Seedling Pod
They Should spawn every 7 seconds and their hp pool should be  23,247k
https://cata-twinhead.twinstar.cz/?npc=40550

Also  both auras should stack on boss from each living Pod
![image](https://user-images.githubusercontent.com/122209088/229148749-94c6286c-57c0-44cc-b40e-4638a4e89061.png)
Also buff is apllied to players and last after boss kill
https://cdn.discordapp.com/attachments/368446147066462219/1091365782727954533/image.png

Currently this boss is not using this ability at all and adds are spawning randomly
![image](https://user-images.githubusercontent.com/122209088/229148986-930dc63c-61f0-484f-80ab-8e804de92f1d.png)

Spores are not moving and cloud is not spawning after their death.
![image](https://user-images.githubusercontent.com/122209088/229149508-6265e966-0182-4256-b2ba-588e12e5f9f4.png)

They should move very slowly and after cloud should spawn that will last 30 secs. Every 1,5 sec cloud is ticking dealing 11699 dmg to player and 15% hp of any Bloodpetal Blossom add that is inside cloud

**Comment by UltraNix** [comment]
Fixed.

**Comment by Sketish** [comment]
This one is still missing

Seedling Pod

They Should spawn every 7 seconds and their hp pool should be 23,247k
https://cata-twinhead.twinstar.cz/?npc=40550
@UltraNix

**Comment by UltraNix** [comment]
Fixed.
