### ISSUE TITLE
First Aid Bandages are on the GCD

### ISSUE THREAD

**Issue by EdyGlockenspiel** [gamefreedomgit/Maelstrom#2934]
**Description:**
Bandages from the First Aid should be off the GCD, just like most other consumables. Currently they are on a GCD like normal abelites. 

**How to reproduce:**
Use any ability with a bandage in your bags and see the bandage get put on GCD

**How it should work:**
Most consumables, including Bandages, should be off the GCD.

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=1159#see-also-ability
https://cata-twinhead.twinstar.cz/?spell=18610
https://www.wowhead.com/wotlk/spell=3268/first-aid

**Comment by UltraNix** [comment]
Fixed.

**Comment by EdyGlockenspiel** [comment]
It's not fixed, maybe using the bandage does not put stuff on CD, but using other stuff puts the bandages on CD. For example, a very popular tactic in pvp is the CC-bandage, this is where you lets say gouge the target as a rogue or fear the target as a warrior and instantly bandage. Right now you can't because your abilities put bandages on CD.

**Comment by Loken-coolguy** [comment]
User reports this was not resolved with recent fix

**Comment by EdyGlockenspiel** [comment]
![image](https://user-images.githubusercontent.com/126888684/232163086-2ce521dd-aa67-47c0-bcc6-673f319736cb.png)
In this SS you can say that my bandage goes on CD when I used horn of winter, that should not be the case. As I mentioned before this prevents popular high end pvp play of instant CC+bandage instantly after like gouge or warrior fear.

**Comment by UltraNix** [comment]
It works okay with >wotlk bandages. Pre-cata bandages still have shared gcd with other abilities. This is clientside and can't be changed.

![image](https://github.com/gamefreedomgit/Maelstrom/assets/80540499/f89415fb-80f0-4952-b28d-d5e729c05570)
