### ISSUE TITLE
[Halls of Origination] Temple Guardian Anhuur - Reverberating Hymn

### ISSUE THREAD

**Issue by Whatisthisclass** [gamefreedomgit/Maelstrom#3236]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
After casting Shield of Light (https://cata-twinhead.twinstar.cz/?spell=80747) Reverberating Hymn (https://cata-twinhead.twinstar.cz/?spell=75322) acts as an Aura, so the damage applies but the boss isn't channeling anything.
After the Players activate both Pillar Levers and Temple Guardian Anhuur's Shield fades, he starts chasing the Tank.

**How to reproduce:**
Engage Temple Guardian Anhuur in Halls of Origination.

**How it should work:**
After casting Shield of Light, Temple Guardian Anhuur should start channeling Reverberating Hymn. 
He should only stop casting it after getting interrupted, which is only possible if he loses his Shield (activating both Levers).
As long as he doesn't get interrupted he shouldn't start attacking again and keep on channeling until he is interrupted or the players wipe.

**Database links:**

**Comment by Alandiel** [comment]
Currently damaging boss interrupts Reverberating Hymn.

**Comment by Whatisthisclass** [comment]
AFAIK he doesn't even channel the spells but it Acts only as an Aura.
Also attacking him of course shouldn't Interrupt it, only interrupts should be able to interrupt it.

But afaik the way he works right now, he doesn't even need to be attacked/interrupted as of right now but he just charges at the players when shield is gone, which obviously is wrong.

There is also a Reference Video here: https://youtu.be/Mxg1Q4xoCYY

**Comment by Whatisthisclass** [comment]
Didn't want to close, my bad.

**Comment by Afgann** [comment]
fixed

**Comment by vajdao** [comment]
@Afgann it might be not fixed. I'm writing from Deathwing, but afaik its the same script. Today I saw people abusing bug. Before boss encounter started, people jump off to the levers, and pull both levers in advance. 
The next time people start fighting the boss and the boss goes into the hymn state, it does not prevent him to take any damage from the party (so the group can still dps, and does not have to go off for the levers ever)
