### ISSUE TITLE
Ring of frost dmg threshold

### ISSUE THREAD

**Issue by Kenniflopper** [gamefreedomgit/Maelstrom#3793]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
Right now currently you can take up to 20% dmg while in a ring of frost which is NOT how its supposed to work

**How to reproduce:**
Cast ring of frost on a player and then use some scorches and see how it doesnt break from direct damage.

**How it should work:**
Ring of frost should not have a damage threshold, it does not break on dots but it should break instantly on direct damage.

**Database links:**
https://www.youtube.com/watch?v=u7W75EXoev4 this video shows how it should work at 2:55 can use 0.25x speed, and also at 13:10 and 13:28

**Comment by mipanka** [comment]
I will add where from the damage of the cone of cold and nova ring dont break. https://youtu.be/AneH1dAtbto?t=567

**Comment by Kenniflopper** [comment]
Thats from aoe which doesnt count as direct damage regarding ring of frost

**Comment by mipanka** [comment]
https://youtu.be/p667ZATEkPY?t=405 here the rogue takes damage from the orb and ring of frost dont break (orb not direct dmg btw)

**Comment by Pornoodemon** [comment]
Question for the experts. And how is it supposed to work with a Soul Link?

**Comment by Kenniflopper** [comment]
Again, it only only breaks on direct damage from a player

**Comment by mipanka** [comment]
https://youtu.be/rPXue4sObxg?t=263 here sham take more than 10% at max hp dmg and ring of frost was break

**Comment by mipanka** [comment]
https://youtu.be/4qsERLrW3_o?t=773 here sham take auto attack at rogue, and after some dmg ring of frost was break, **but 100% not first!** therefore, should not from the first direct damage

**Comment by UltraNix** [comment]
https://github.com/gamefreedomgit/Maelstrom/issues/3797#issuecomment-1592555083

**Comment by UltraNix** [comment]
Fixed.

**Comment by VincentADK** [comment]
I have people on discord that claim that this isn't fixed yet.
Is there a possibility maybe, that it could get checked again please?

**Comment by UltraNix** [comment]
@mipanka Can you tell how big is the diff between 20% of max hp vs 20% of base hp on our server? I mean: how much **base** hp you have and how much hp you have in the normal pvp match (arena/bg)?

**Comment by mipanka** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/88f85277-2e40-4d9a-81a9-5fd3fcece5ca) here without gear base hp)
![image](https://github.com/gamefreedomgit/Maelstrom/assets/127995853/a67c64bd-07a4-424b-90f6-227e6dd52bfb) here bg gear

**Comment by mipanka** [comment]
I saw you did 20% of base health, why not 10% of max health? As it was before all fixes

**Comment by UltraNix** [comment]
Because it's not 10%., e.g. on videos you linked here (and on other videos linked on different reports).

**Comment by mipanka** [comment]
https://youtu.be/rPXue4sObxg?t=500 
128k >125k>128k>125k>131k>130k>124k > nova is not broken > next hit broken (115k)
3+3+1+6=**13k** hp minimum threshold 
max hp 161k / 10% =**16.1k**
base hp priest 44k / 20% = **8.8k**
_does not converge_

**Comment by UltraNix** [comment]
As I can see, it's not static 10% of max hp or 20% of base hp.

**Comment by mipanka** [comment]
So, this will be implemented dynamically from 20% to 40%?
In addition, the base health of different classes is different, and in the future, maximum health will increase by about 40% of the items. 
I donk know why all think about 10% of max hp, Im too also think, but, mb bcs anothet private servers its work also with 10% and we/I mistake in this.

**Comment by UltraNix** [comment]
It's gonna be 20% of base health - it's minimum dmg threshold.
40% of base health - it's maximum dmg threshold.
Once you brake 20%, then you have 13% (for DOTs it's 5%) chance to break right there and until you hit 40%.
Once you hit 40% - then aura is removed immediately.

**Comment by Pornoodemon** [comment]
> It's gonna be 20% of base health - it's minimum dmg threshold. 40% of base health - it's maximum dmg threshold. Once you brake 20%, then you have 13% (for DOTs it's 5%) chance to break right there and until you hit 40%. Once you hit 40% - then aura is removed immediately.

I hope this change does not affect fear effects? After the last change, in my opinion, fear works ideally.

**Comment by Pornoodemon** [comment]
As for the ring of frost, this mechanic is unlikely to apply here, since the calculation from base and maximum hp are different things and this spell does not break from pillboxes.
Most likely the ring of frost just the same has a threshold of 10% of max hp
In addition, after a freeze break, there must be at least 5 seconds of immunity to exit the frost ring.

7:57
https://www.youtube.com/watch?v=OS0u1op2C7s
  The video shows how, after the spell breaks, the player walks along the ring for 5 seconds and then freezes again.

**Comment by Pornoodemon** [comment]
The ring of frost should have a fixed threshold, and the variability of damage dealt to the enemy under the influence of the ring of frost in the video is caused by the different amount of maximum health for the players and the incorrect calculation of damage  from the last threshold breaking blow

**Comment by mipanka** [comment]
Ofc for fear too. Its for all fears, frost nova, ring of frost and hex

**Comment by mipanka** [comment]
> > It's gonna be 20% of base health - it's minimum dmg threshold. 40% of base health - it's maximum dmg threshold. Once you brake 20%, then you have 13% (for DOTs it's 5%) chance to break right there and until you hit 40%. Once you hit 40% - then aura is removed immediately.
> 
> I hope this change does not affect fear effects? After the last change, in my opinion, fear works ideally.

After first freeze, player have 3 sec delay for new freeze

**Comment by mipanka** [comment]
> As for the ring of frost, this mechanic is unlikely to apply here, since the calculation from base and maximum hp are different things and this spell does not break from pillboxes. In addition, calculations on base hp 20-40% are something from lich king. Most likely the ring of frost just the same has a threshold of 10% of max hp the variability of damage dealt to the enemy under the influence of the ring of frost in the video is caused by the different amount of maximum health for the players and the incorrect calculation of damage from the last threshold breaking blow In addition, after a freeze break, there must be at least 5 seconds of immunity to exit the frost ring.
> 
> 7:57 https://www.youtube.com/watch?v=OS0u1op2C7s The video shows how, after the spell breaks, the player walks along the ring for 5 seconds and then freezes again.

After first freeze, player/enemy have 3 sec delay before will be new freeze

**Comment by UltraNix** [comment]
Yes - all breakable CC auras with dmg threshold will change that formula.

**Comment by UltraNix** [comment]
Fixed.
