### ISSUE TITLE
Supporting the Troops kills don't count.

### ISSUE THREAD

**Issue by Corvexus** [gamefreedomgit/Maelstrom#3955]
**Description:**
Regarding the Quest **Supporting the Troops** (27085) in the Western Plaguelands.
The **Andorhal Defender**s don't count towards your quest counter, even if you tag them before any other creature attacks them.

**How to reproduce:**
Play any horde character, accept quest, go kill any **Andorhal Defender**, see that the counter stays at **0**.

**How it should work:**
Play any horde character, accept quest, go kill any **Andorhal Defender**, see that the counter goes **+1**. (until it reaches 15)

**Database links:**
https://cata-twinhead.twinstar.cz/?quest=27085

**Comment by Afgann** [comment]
fixed

**Comment by mserkanoz** [comment]
It is still not working.

**Comment by KevlinTallfellow** [comment]
Killing the alliance defenders in Andorhal still doesn't give quest credit as of 12/09/2023
