### ISSUE TITLE
[warrior] Charge

### ISSUE THREAD

**Issue by mipanka** [gamefreedomgit/Maelstrom#4093]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
when warrior use charge, he can be stopped on half way

**How to reproduce:**
use charge and use target stun or some cc in warrior, he will be stopped before will reach target

**How it should work:**
warrior should will reach target, but cc should not stopped him. If he get cc should be in cc and continue charge

**Database links:**
https://wowpedia.fandom.com/wiki/Charge

**Comment by Pornoodemon** [comment]
https://www.youtube.com/watch?v=r8x0kjm4iwU&t=108s

**Comment by VirtualReign** [comment]
Perhaps related to the Death Knight's Death Grip often pulling enemies only half way instead into the Death Knight's melee range.

**Comment by Pornoodemon** [comment]
There can be many different questions here.
For example, let's imagine a situation where a warrior makes a charge someone and after that, in a split second, Dk uses a death grip.
The question is, where should the warrior be? In fact, near the DK, but according to this mechanic, he should be near the enemy to whom he makes a charge.
It seems to me that this problem appears to a greater extent due to the ping and the position of the player (from a program point of view).

**Comment by UltraNix** [comment]
Fixed.

**Comment by Qidpuncher-outland** [comment]
Was this confirmed fixed ? Since the same should apply to leap as well

**Comment by Hermeleen** [comment]
Pretty sure this is not fixed. Although i am not at pc at the moment,  i vividly remember probably ten days ago, charging to a target approximately 15-20 yards in front of me, and getting rooted by snake trap after charging the first 2-3 yards.

**Comment by bonfax4** [comment]
This doesn't seem to be valid for all spells, or maybe the cc type or timing matters.I can see death coil stopping charge [here](https://youtu.be/Ji9Yf7s28oY?t=5m40s)
