### ISSUE TITLE
"King of the Spider-Hill" achievement impossible to complete

### ISSUE THREAD

**Issue by MarioVrenzola** [gamefreedomgit/Maelstrom#4277]
Description: One of the last spiders is not in the correct position (yellow circle on the first screenshot below) making it impossible to complete the achievement without some form of mobility
![WoWScrnShot_082223_150950](https://github.com/gamefreedomgit/Maelstrom/assets/133254960/2d74ef49-ebed-4780-a110-8bf8b5e78ab7)

How to reproduce: go there and see

How it should work: there should be a spider on the circled pillar that grips you up once you aggro him

The Achievement: https://www.wowhead.com/achievement=5872/king-of-the-spider-hill

**Comment by Wick3dmind** [comment]
Not true it is possible to complete, i have done it.

**Comment by SexyPancake** [comment]
Done 2 days ago on a mage without any guardian/pet/player involved. Current issue is spiders falling off their position (could be blizzlike or not, idk).

**Comment by UltraNix** [comment]
Fixed.

**Comment by lebombas** [comment]
![image](https://github.com/gamefreedomgit/Maelstrom/assets/143462139/041d7fad-0a9e-401e-abe6-a6cd5ea99013)
 not fixed
