### ISSUE TITLE
[WotLK] [Achievment] [Quest] Loremaster of Northrend Horde report

### ISSUE THREAD

**Issue by Aurorre** [gamefreedomgit/Maelstrom#5017]
### After discussing it with a few people of the server I compiled all my separate posts into one for a total overview.

During my hunt for the Loremaster title this is what I came across in Northrend as Horde. Without some of these quest chains [Loremaster of Northrend](https://www.wowhead.com/achievement=41/loremaster-of-northrend) is unachievable.

### **_Howling Fjord [I've Toured the Fjord](https://www.wowhead.com/achievement=1356/ive-toured-the-fjord)_**

[Warning: Some Assembly Required](https://www.wowhead.com/wotlk/quest=11310):
When you explode the Abomination it doesn't count towards the quest.

[The Dead Rise](https://www.wowhead.com/quest=11504):
[Orfus of Kamagua](https://www.wowhead.com/npc=23804/orfus-of-kamagua) The quest-giver doesn't have the exclamation mark (!) above him so big part of the quest-line towards the achievement falls away.

[Forgotten Treasure](https://www.wowhead.com/quest=11434):
[Handsome Terry](https://www.wowhead.com/npc=24537/handsome-terry) Same as Orfus doesn't give the exclamation mark (!).

[Spirit of the ice](https://www.wowhead.com/wotlk/quest=11313/spirits-of-the-ice):
[Lurielle](https://www.wowhead.com/wotlk/npc=24117/lurielle) Same as Orfus and Handsome Terry doesn't give the exclamation mark (!).

### **_Dragonblight [Might of Dragonblight](https://www.wowhead.com/achievement=1359/might-of-dragonblight)_**

[A Fall From Grace](https://www.wowhead.com/wotlk/quest=12274):
The quest could be completed in the quest log but can't be deliver to the quest giver [Agent Skully](https://www.wowhead.com/wotlk/npc=27350/agent-skully) (says continue but when you click it nothing happens).

[One of a Kind!](https://www.wowhead.com/wotlk/quest=12148):
The exclamation mark (!) doesn't show up above [Aurastrasza](https://www.wowhead.com/wotlk/npc=26983/aurastrasza).

[Mystery of the Infinite, Redux](https://www.wowhead.com/wotlk/quest=13343):
[Chromie](https://www.wowhead.com/wotlk/npc=27856/chromie) gives the quest plus item, When the item [Hourglass of Eternity](https://www.wowhead.com/wotlk/item=44450/hourglass-of-eternity) Gets placed, nothing happens (tried 3 times).

[Report to Lord Devrestrasz](https://www.wowhead.com/wotlk/quest=12435):
The exclamation mark (!) doesn't show up above [Alexstrasza the Life-Binder](https://www.wowhead.com/wotlk/npc=26917/alexstrasza-the-life-binder).

[Imbeciles Abound!](https://www.wowhead.com/wotlk/quest=12189):
The exclamation mark (!) doesn't show up above [Doctor Sintar Malefious](https://www.wowhead.com/wotlk/npc=26505/doctor-sintar-malefious).

[The Kor'kron Vanguard!](https://www.wowhead.com/wotlk/quest=12224):
The exclamation mark (!) doesn't show up after completing all previous quests above [Overlord Agmar](https://www.wowhead.com/wotlk/npc=26379/overlord-agmar).

### **_Borean Tundra [Nothing Boring About Borean](https://www.wowhead.com/achievement=1358/nothing-boring-about-borean)_**

[Taking Back Mightstone Quarry](https://www.wowhead.com/wotlk/quest=11598):
The question mark (!)doesn't show up above [Overlord Razgor](https://www.wowhead.com/wotlk/npc=25279/overlord-razgor).

[Magic Carpet Ride](https://www.wowhead.com/wotlk/quest=11636/magic-carpet-ride):
Talked to [Yanni](https://www.wowhead.com/wotlk/npc=25459/yanni) for the ride, Get mounted on carpet, doesn't auto-fly and have to fly yourself. When reaching the quest point at Previous known as Gorge the Corpsegrinder now [Annihilator Grek'lor](https://www.wowhead.com/wotlk/npc=25329/annihilator-greklor) You can't deliver the quest.

[Bring 'Em Back Alive](https://www.wowhead.com/wotlk/quest=11690):
You can jump on the kodo but not move them back to the quest giver [Farmer Torp](https://www.wowhead.com/wotlk/npc=25607/farmer-torp).

[Nork Bloodfrenzy's Charge](https://www.wowhead.com/wotlk/quest=11709):
[Garrosh Hellscream](https://www.wowhead.com/wotlk/npc=25237/garrosh-hellscream) doesn't have exclamation mark (!) after the required quests are done.

[Karuk's Oath](https://www.wowhead.com/wotlk/quest=11613):
[Karuk](https://www.wowhead.com/wotlk/npc=25435/karuk) has no exclamation mark (!) above him.

[Prison Break](https://www.wowhead.com/wotlk/quest=11587):
[Librarian Donathan](https://www.wowhead.com/wotlk/npc=25262/librarian-donathan) has no exclamation mark (!) above him.

[Learning to Communicate](https://www.wowhead.com/wotlk/quest=11571):
[King Mrgl-Mrgl](https://www.wowhead.com/wotlk/npc=25197/king-mrgl-mrgl) doesn't have exclamation mark (!) above him.

[Escape from the Winterfin Caverns](https://www.wowhead.com/wotlk/quest=11570):
Walk with [Lurgglbr](https://www.wowhead.com/wotlk/npc=25208/lurgglbr) till the end point, there he just de-spawns and not getting marked as complete.

[Kaganishu](https://www.wowhead.com/wotlk/quest=11637):
When using [Kaganishu's Fetish](https://www.wowhead.com/wotlk/item=34781/kaganishus-fetish) on [Farseer Grimwalker's Spirit](https://www.wowhead.com/wotlk/npc=25425/farseer-grimwalkers-spirit) it doesn't set him free thus can't be completed.

[Across Transborea](https://www.wowhead.com/wotlk/quest=11930):
Taunka'le Evacuee follows you, but can't deliver quest at [Wartook Iceborn](https://www.wowhead.com/wotlk/npc=26156/wartook-iceborn) since it doesn't give complete credit.

### **_Grizzly Hills [Fo' Grizzle My Shizzle](https://www.wowhead.com/achievement=1357/fo-grizzle-my-shizzle)_**

[Filling the cages](https://www.wowhead.com/wotlk/quest=11984) :
[Samir](https://www.wowhead.com/wotlk/npc=26424/samir) doesn't have an exclamation mark (!) after delivering [Good troll hunting](https://www.wowhead.com/wotlk/quest=12208).

[Ruunas Request](https://www.wowhead.com/wotlk/quest=12328):
[Ruuna the Blind](https://www.wowhead.com/wotlk/npc=27581/ruuna-the-blind) doesn't have an exclamation mark (!) after delivering [https://www.wowhead.com/wotlk/quest=12425/ruuna-the-blind](https://www.wowhead.com/wotlk/quest=12425).

[The Horse Hollerer](https://www.wowhead.com/wotlk/quest=12415):
Throwing [Flashbang Grenade](https://www.wowhead.com/wotlk/item=37716/flashbang-grenade) at the Mustangs, they don't run away frightened.

[Raining Down Destruction](https://www.wowhead.com/wotlk/quest=11982):
[Kurun](https://www.wowhead.com/wotlk/npc=26260/kurun) doesn't have an exclamation mark (!) after delivering [An Expedient Ally](https://www.wowhead.com/wotlk/quest=12074). It did work after a gm gave the alliance version [Find Kurun](https://www.wowhead.com/wotlk/quest=11981).

[Rallying the Troops](https://www.wowhead.com/wotlk/quest=12070/rallying-the-troops):
Again [Kurun](https://www.wowhead.com/wotlk/npc=26260/kurun) doesn't have an exclamation mark(!) after completing [Raining Down Destruction](https://www.wowhead.com/wotlk/quest=11982). Maybe they linked wrong somewhere because different faction?

### **_Zul'Drak[The Empire of Zul'Drak](https://www.wowhead.com/achievement=36/the-empire-of-zuldrak)_**

[Infiltrating Voltarus](https://www.wowhead.com/wotlk/quest=12661): 
[Stefan Vadu](https://www.wowhead.com/wotlk/npc=28518/stefan-vadu) doesn't have an exclamation mark (!) after completing [Dressing Down](https://www.wowhead.com/wotlk/quest=12648).

[That's What Friends Are For](https://www.wowhead.com/wotlk/quest=12903):
[Gerk found](https://www.wowhead.com/wotlk/npc=29455/gerk) but it doesn't make it complete in the log or at [Crusader MacKellar](https://www.wowhead.com/wotlk/npc=29689/crusader-mackellar).

[Light Won't Grant me Vengeance](https://www.wowhead.com/wotlk/quest=12904): 
[Gerk](https://www.wowhead.com/wotlk/npc=29455/gerk) doesn't have the exclamation mark (!).

Getting the quest [So Far So Bad](https://www.wowhead.com/wotlk/quest=12669) from [Stefan Vadu](https://www.wowhead.com/wotlk/npc=28518/stefan-vadu) (Side issue: didn't work on his dragon so had to go to Ebon Watch) doesn't give me the [Overlord Drakuru](https://www.wowhead.com/wotlk/npc=28503/overlord-drakuru) task [It Rolls Downhill](https://www.wowhead.com/wotlk/quest=12673).

[Hazardous Materials](https://www.wowhead.com/wotlk/quest=12677): 
Same issue, [Overlord Drakuru](https://www.wowhead.com/wotlk/npc=28503/overlord-drakuru) doesn't give the task [Zero Tolerance](https://www.wowhead.com/wotlk/quest=12686).

[Sabotage](https://www.wowhead.com/wotlk/quest=12676): 
Use [Explosive Charges](https://www.wowhead.com/wotlk/item=39165/explosive-charges), Blows up the wagon doesn't give credit and again the same issue, [Overlord Drakuru](https://www.wowhead.com/wotlk/npc=28503/overlord-drakuru) doesn't give the task [Fuel for the Fire](https://www.wowhead.com/wotlk/quest=12690) thus not being able to do the quest [Disclosure](https://www.wowhead.com/wotlk/quest=12710) after to complete [Sabotage](https://www.wowhead.com/wotlk/quest=12676).

[The Key of Warlord Zol'Maz](https://www.wowhead.com/wotlk/quest=12712): 
You can summon [Warlord Zol'maz](https://www.wowhead.com/wotlk/npc=28902) but he is not attackable.

[Pa-troll](https://www.wowhead.com/wotlk/quest=12596): 
Can't be completed by multiple fractions from [Commander Kunz](https://www.wowhead.com/wotlk/npc=28039/commander-kunz) can't be completed (I assume also all the daily versions won't work, If I have to post all those it will be a really long post).

[Captain Brandon](https://www.wowhead.com/wotlk/npc=28042/captain-brandon) doesn't have quest [Something For The Pain](https://www.wowhead.com/wotlk/quest=12597) for [Pa-troll](https://www.wowhead.com/wotlk/quest=12596).

[Captain Grondel](https://www.wowhead.com/wotlk/npc=28043/captain-grondel) doesn't have quest [Creature Comforts](https://www.wowhead.com/wotlk/quest=12599) for [Pa-troll](https://www.wowhead.com/wotlk/quest=12596).

[Alchemist Finklestein](https://www.wowhead.com/wotlk/npc=28205/alchemist-finklestein) doesn't have quest [Lab Work](https://www.wowhead.com/wotlk/quest=12557) for [Pa-troll](https://www.wowhead.com/wotlk/quest=12596).

### **_Sholazar Basin [Into the Basin](https://www.wowhead.com/achievement=39/into-the-basin)_**

[The Mist Isn't Listening](https://www.wowhead.com/wotlk/quest=12538):
The npc's ([Mistwhisper Gorloc](https://www.wowhead.com/wotlk/npc=28109/mistwhisper-warrior)) you need to kill are invalid when you want to attack.

[Forced Hand](https://www.wowhead.com/wotlk/quest=12576):
The npc's (6x [Frenzyheart Scavenger](https://www.wowhead.com/wotlk/npc=28081/frenzyheart-scavenger) and 8x [Frenzyheart Spearbearer](https://www.wowhead.com/wotlk/npc=28080/frenzyheart-spearbearer)) you need to kill are invalid when you want to attack.

### [Frenzyheart Tribe](https://www.wowhead.com/wotlk/?faction=1104) Daily's:

[Tools of War](https://www.wowhead.com/wotlk/quest=12759):
[Sparktouched Gorloc](https://www.wowhead.com/wotlk/npc=28111/sparktouched-warrior) are un-attackable.

[Kartak's Rampage](https://www.wowhead.com/wotlk/quest=12703):
[Sparktouched Gorloc slain](https://www.wowhead.com/wotlk/npc=28111/sparktouched-warrior) are un-attackable.

[Secret Strength of the Frenzyheart](https://www.wowhead.com/wotlk/quest=12760):
[Sparktouched Gorloc](https://www.wowhead.com/wotlk/npc=28111/sparktouched-warrior) are un-attackable.

### [The Oracles](https://www.wowhead.com/wotlk/?faction=1105) Daily's:

[Will of the Titans](https://www.wowhead.com/wotlk/quest=12705):
[Frenzyheart Attacker](https://www.wowhead.com/wotlk/npc=28078/frenzyheart-ravager) are un-attackable.

[Power of the Great Ones](https://www.wowhead.com/wotlk/quest=12762/power-of-the-great-ones):
[Frenzyheart Attacker](https://www.wowhead.com/wotlk/npc=28078/frenzyheart-ravager) un-attackable.

[Mastery of the Crystals](https://www.wowhead.com/wotlk/quest=12761):
[Frenzyheart Attacker](https://www.wowhead.com/wotlk/npc=28078/frenzyheart-ravager) un-attackable.

[Song if Fecundity](https://www.wowhead.com/wotlk/quest=12737):
There are no Soak Fertile Dirt spawns.

### **_Storm Peaks [The Summit of Storm Peaks](https://www.wowhead.com/achievement=38/the-summit-of-storm-peaks)_**

The [Lok'lira's Bargain](https://www.wowhead.com/wotlk/spell=72914) keeps phasing in and out in Brunnhildar Village that you have to leave village and come back.

[Krolmir, Hammer of Storms](https://www.wowhead.com/wotlk/quest=13010):
When going trough the dialog of [King Jokkum](https://www.wowhead.com/wotlk/npc=30105) You mount on him but he doesn't bring you to the quest spot. When you travel there yourself no further dialog and/or [Thorim](https://www.wowhead.com/wotlk/npc=29445) there for the follow-up quest.

[Sniffing Out the Perpetrator](https://www.wowhead.com/wotlk/quest=12910):
When you mount the Frost Saber, It doesn't auto walk and doesn't have attacks/get attacked. When at the location [Tracker Thulin](https://www.wowhead.com/wotlk/npc=29695) doesn't spawn to give [Brann's Communicator](https://www.wowhead.com/wotlk/item=40971) by loot.

[Changing the Wind's Course](https://www.wowhead.com/wotlk/quest=13058): 
When using [The Lorehammer](https://www.wowhead.com/wotlk/item=42918) It spawns [Stormhoof](https://www.wowhead.com/wotlk/npc=30388) but doesn't put you in his shoes to attack [The North Wind](https://www.wowhead.com/wotlk/npc=30474) to get the [Horn of Elemental Fury](https://www.wowhead.com/wotlk/object=194123) After spawning like 100's of Stormhoof's I found out that you can put yourself in his shoes in the cave (The Howling Hollow) behind "The Plain Echoes" (as the quest describes). That is a pretty misplaced location.

[Cold Hearted](https://www.wowhead.com/wotlk/quest=12856):
You can deliver [Rescued Brunnhildar Prisoners](https://www.wowhead.com/wotlk/npc=29734/liberated-brunnhildar) but it doesn't count for [Freed Proto-Drakes](https://www.wowhead.com/wotlk/npc=29709/freed-proto-drake). Also you have to fly yourself and not auto fly once you leave Dun Niffelem.

Quest [Battling the Elements](https://www.wowhead.com/wotlk/quest=12967): 
Can't be completed since there are no snow bumps to pick up.

### [The Sons of Hodir](https://www.wowhead.com/wotlk/faction=1119/the-sons-of-hodir) Daily's.

Quest (daily) [Feeding Arngrim](https://www.wowhead.com/wotlk/quest=13046): 
Can't be completed since [Roaming Jormungar](https://www.wowhead.com/wotlk/npc=30422) don't get the debuff.

Quest [Thrusting Hodir's Spear](https://www.wowhead.com/wotlk/item=42769) and the daily [How To Slay Your Dragon](https://www.wowhead.com/wotlk/quest=13003): 
Can't be completed since [Wild Wyrm Slain](https://www.wowhead.com/wotlk/npc=30415/wild-wyrm-kc-bunny) are not targateble.

### **_Icecrown [Icecrown: The Final Goal](https://www.wowhead.com/achievement=40/icecrown-the-final-goal)_**

[Into The Wild Green Yonder](https://www.wowhead.com/wotlk/quest=13045):
Mounted on the protodrake but can't rescue [Captured Crusader Rescuer](https://www.wowhead.com/wotlk/npc=30407) when clicking on the "Grab Captured Crusader"
After further testing I could just hoover above the rescue spot and spam the drop off button and it counted without having to leave the area.

[The Last Line Of Defence](https://www.wowhead.com/wotlk/quest=13086):
Can spam Reckoning bomb without charging it first.

[Before the Gate of Horror](https://www.wowhead.com/wotlk/quest=13335):
Throwing [Volatile Acid](https://www.wowhead.com/wotlk/item=44653) doesn't count towards quest after killing [Skeletal Reaver bones dissolved](https://www.wowhead.com/wotlk/npc=32288).

[Baron Sliver](https://www.wowhead.com/wotlk/npc=29343): 
Doesn't have the followup quest [I Have an Idea, But First...](https://www.wowhead.com/wotlk/quest=12891).

[Baron Sliver](https://www.wowhead.com/wotlk/npc=29343) doesn't give the followup quest [The Duke](https://www.wowhead.com/wotlk/quest=12938). after completing [The Shadowvault](https://www.wowhead.com/wotlk/quest=12899).

[Revenge for the Vargul](https://www.wowhead.com/wotlk/quest=13059):
When you start the event Volgur can not be attacked.

[Army of the Damned](https://www.wowhead.com/wotlk/quest=13236): 
When using the rise ghoul as Arthas it doesn't count towards the quests.

[Parting Gifts](https://www.wowhead.com/wotlk/quest=13168):
When you click the Eye of Dominion and get to be an [Eidolon Watcher](https://www.wowhead.com/wotlk/npc=30947), it doesn't complete in the log.

[An Undead's Best Friend](https://www.wowhead.com/wotlk/quest=13169):
When feeding the plague hounds with the skill from the [Eidolon Watcher](https://www.wowhead.com/wotlk/npc=30947) it doesn't count up (the do become friendly).

[From Whence They Came](https://www.wowhead.com/wotlk/quest=13171):
When using the skill on the [Banished Scourge Crystals](https://www.wowhead.com/wotlk/npc=31131) with the [Eidolon Watcher](https://www.wowhead.com/wotlk/npc=30947), it doesn't count up (they do dissapear).

[Honor is for the Weak](https://www.wowhead.com/wotlk/quest=13170):
When attacking [Restless Lookouts assassinated](https://www.wowhead.com/wotlk/npc=30951) They can't be killed when you are an [Eidolon Watcher](https://www.wowhead.com/wotlk/npc=30947). Can be killed without.

[New Recruit](https://www.wowhead.com/wotlk/quest=13143):
When subjugate a Lithe Stalker It doesn't follow you nor can you deliver it to [Vereth the Cunning](https://www.wowhead.com/wotlk/npc=30944).

[King of the Mountain](https://www.wowhead.com/wotlk/quest=13283):
Can't be completed since the jumps don't work.

I want to thank all the GM's that helped me mapping out the horde story lines of Northrend.

**Comment by PanJanuszek** [comment]
Fixed along with @MrTide list

**Comment by Seryphus** [comment]
Just found the Kaganishu quest in Borean Tundra is still not freeing the quest npc preventing completion
