### ISSUE TITLE
shapeshift vs glyph of frostfire

### ISSUE THREAD

**Issue by SimonBpvp** [gamefreedomgit/Maelstrom#5043]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**
![image](https://github.com/gamefreedomgit/Maelstrom/assets/94299191/70b3013c-96d2-40c0-b655-5e35830a8653)
you can shapeshift this debuff off even though with the glyph it's a dot and not a slow

**How to reproduce:**
hit a druid with frostfire bolt and then let him shapeshift

**How it should work:**
it shouldn't dispel the dot, it should only clean the unglyphed slow

**Database links:**
https://cata-twinhead.twinstar.cz/?spell=61205

**Comment by mipanka** [comment]
Btw need to test with vanish

**Comment by UltraNix** [comment]
Fixed.

**Comment by mipanka** [comment]
@UltraNix bug still here, all abilities who can dispel slow/root, too dispeled this debuff. I tested with vanish, cleanse ret pala, and freedom

**Comment by UltraNix** [comment]
@mipanka New report needed.

**Comment by bonfax4** [comment]
@Ultranix Btw this is not a bug. I've seen shapeshift remove the debuff in videos. 

You can use this video as evidence :

https://youtu.be/UnGImLYzujY?t=3m1s slow down the video to 0.25 and you can confirm he has the glyph because you see 1 tick of 67 dmg. He goes bear form later and the debuff is removed.

**Comment by mipanka** [comment]
https://github.com/gamefreedomgit/Maelstrom/assets/127995853/71723561-7874-4b06-9162-8c65e2c5dc3f

as example with vanish, dont work

**Comment by bonfax4** [comment]
Highly doubt it's supposed to work tho, it's still considered a slow, even if it's 0%. For shapeshift in retail.

**Comment by bonfax4** [comment]
Think the other spells needs video confirmation because it's inconsistent from both our clips. Vanish does not remove the glyphed dot but shapeshift did.

**Comment by UltraNix** [comment]
I'm confused rn. Why vanish should remove that DoT? If it's glyphed, it's no longer slow.

**Comment by UltraNix** [comment]
So I'm confused right now :) Looks like only shapeshift should remove - do we have any proof of that from retail?

**Comment by UltraNix** [comment]
For me it looks like there is no bug here and I should revert it.

**Comment by bonfax4** [comment]
Yh shapeshift should remember Ve it regardless yes. Rest of the spells I dunno. Seems to be a case by case basis

**Comment by bonfax4** [comment]
https://youtu.be/iRwa2Te_CuY?t=1m1s masters call on pet doesn't remove the glyphed version either. Maybe there's some similarity in the coding between which spells do and don't ?

**Comment by UltraNix** [comment]
Not really. Vanish, shapeshifts, Pvp trinkets, Master's Call - all of these spells removes auras with specific mechanic. In that case, it's snare mechanic and the DoT has it.

**Comment by bonfax4** [comment]
Well no idea then, I do see shapeshifting  words it differently but that doesn't explain why the pvp trinket does it. But from what mipanka said all abilities are removing it currently ? So I dunno if every other ability removing came after this change.

**Comment by UltraNix** [comment]
Make some generic solution.

**Comment by bonfax4** [comment]
Well [shaman](https://youtu.be/5U1KNPcThtc?si=qRh9qVoOcY_mTsHg) with earthbind totem talent that removes snares also doesn't remove it... Neither does warlock teleport...

**Comment by bonfax4** [comment]
@UltraNix Think you somehow gotta make an exception to shapeshift and pvp trinket only.

**Comment by UltraNix** [comment]
Fixed.
