### ISSUE TITLE
Hour of Twilight- Add Faceless Shadow weaver

### ISSUE THREAD

**Issue by loboxter** [gamefreedomgit/Maelstrom#5072]
**Description:**: This Npc is casting an ability incorrectly, as seeking shadows should randomly mark a member of the party and after four seconds take the damage in 8 yards around the target, however in the video you can see how he is throwing it only at the tank and what is worse, he is throwing it instantly so he does not give time to react   (It should be added that the damage of the ability is correct)

I'll leave a Youtube link so you can see that the NPC is casting his spell instantly and only at the tank (which shouldn't be the case, but randomly) and that he doesn't mark any target with debuff either, but simply takes the damage instantly and doesn't have time to react    https://www.youtube.com/watch?v=0p8UIRixzUQ&ab_channel=SebasLobo

**How to reproduce:** Just take on him and you'll see how much damage he's doing to the tank and melee dps with no ability to react

**How it should work:** He should mark a random target in the group and after four seconds take the damage in 8 yards around him and not take the damage instantly

**Database links:** Here's the tick that should appear on the target randomly: https://www.wowhead.com/spell=102983/seeking-shadows     
   Here's the ability that does the damage at 8 yards to the random target: https://www.wowhead.com/es/spell=102984/sombras-rastreadoras#sounds

**Comment by UltraNix** [comment]
Fixed.

**Comment by JK2M** [comment]
no it is not fixed, Weaver still instantly casts do incredible Dmg and just runs around and throw Shadow Bolts in over 50 Yards Range, somehow Marks come up but do nothing, its still completly bugged

**Comment by UltraNix** [comment]
Seeking Shadows can mark you up to 60 yards away the mob.
