### ISSUE TITLE
Morchok - Stomp and crystal timer

### ISSUE THREAD

**Issue by Polynomix** [gamefreedomgit/Maelstrom#5621]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (http://wowhead.com/)
[//]: # (cata-twinhead.twinstar.cz)

**Description:**

If bosses are split before the first stomp, first stomp should not be from Kohcrom. Also cd between 2 stomps is too short, that makes it so that the stomp and the crystal explosion happen at the same time. 

**How to reproduce:**

pull boss, watch who does stomp first, watch when stomp/crystal detonation happens

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/3d654e5d-4ae2-473d-af98-9cfd1924c0ec)

![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/e2b2b36a-8f02-423d-9bee-ce44e4d2db4f)
this should not happened

**How it should work:**

morchok should be first to cast his abilities
if there is a stomp before split : stomp before split -> split -> stomp -> crystal -> stomp -> crystal -> interphase
if there is no stomp before split : split -> stomp -> stomp -> crystal -> stomp -> crystal -> interphase
after interphase :  stomp -> stomp ->  crystal -> stomp -> crystal -> stomp ->crystal -> interphase

(when i say crystal i'm referring to the crystal detonating, not the spawn)

also kohcrom skips first stomp if split before stomp and crystal if split after. At the start of each interphase he skips first crystal

https://www.youtube.com/watch?v=H8JStl_lyKE
https://www.youtube.com/watch?v=IX967tL21l4
https://www.youtube.com/watch?v=11wZn7WtEaI
https://youtu.be/BKNx6q0s1Gk

**Database links:**

[Stomp](http://cata-shoot.tauri.hu/?spell=103414)
[Crystal](http://cata-shoot.tauri.hu/?spell=110040)

**Comment by UltraNix** [comment]
First Morchok Stomp is done on 12 sec, so it's never Kohcrom doing the 1.st Stomp.

**Comment by Polynomix** [comment]
![301927888-3d654e5d-4ae2-473d-af98-9cfd1924c0ec](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/02ef40fd-17fd-4e01-bf5d-5c727faa6496)

this is happening every pull

**Comment by Polynomix** [comment]
https://clips.twitch.tv/MotionlessBetterCrocodileDxCat-xx-EDR3wUS1OGHsj
https://clips.twitch.tv/HorribleTangibleBubbleteaNotATK-4JTjA4TrG2OV1zTE
https://clips.twitch.tv/CrunchyExuberantFriesYouDontSay-4U8guY7oSPHN1YU_
https://clips.twitch.tv/CarelessWiseCrabsBudBlast-FQNRunjmydlTSrAV

**Comment by Revly** [comment]
> First Morchok Stomp is done after 12 sec, so it's never Kohcrom doing the 1.st Stomp. I see no bug here with this.

There are times when Kohcrom is the one who initiates the stomps and not Morchok, it's rare but that's how it happens...

**Comment by Polynomix** [comment]
timer are still off : 
![image](https://github.com/gamefreedomgit/Maelstrom/assets/133067357/8a55bca1-c943-40e5-893b-ce01e65c012a)
i believe that's because stomp timer is still too short (10.5s right now, its more like 12-14s in all those videos)
also he stomps a 5th time right before earthern vortex when it should not

**Comment by UltraNix** [comment]
@Polynomix Yep - first Stomp is 12 sec and then 10.5. Will be fixed.

**Comment by UltraNix** [comment]
Fixed.

**Comment by Polynomix** [comment]
> also he stomps a 5th time right before earthern vortex when it should not

This is still happening; and for the first phase before the first black blood phase, its the 4th stomps that shouldn't happen

**Comment by Polynomix** [comment]
also, the last crystal form kohcrom is detonating during earthern vortex cast. In all those videos earthen vortex cast happens 1min after pull. Here its happening 55s into the pull, maybe that's why.

**Comment by UltraNix** [comment]
Fixed.
