### ISSUE TITLE
Achievemet: Experienced Drake Rider

### ISSUE THREAD

**Issue by beldy69** [gamefreedomgit/Maelstrom#5803]
Hi, we were doing The Oculuss achievement, where we are supposed to kill the last boss (drake) with 3 variatons of drakes. We did it with Amber Drakes and we didnt completed that part of achiev. GM said its not scripted right... 

HIGH PRIORITY, WANT MY MOUNT PLEASE

Yours sincerely Beldy ^^

**Comment by PanJanuszek** [comment]
On **three different visits** to The Oculus, get credit for defeating Ley-Guardian Eregos while riding an Amber, Emerald, and Ruby drake on Heroic Difficulty.

**Comment by PanJanuszek** [comment]
Each of you has to do oculus 3x times with each variation.

**Comment by PanJanuszek** [comment]
But yes, it doesnt count personally in achvievement criteria

**Comment by PanJanuszek** [comment]
fixed 25.03.2024

**Comment by beldy69** [comment]
Hey... Its still not fixed. Ive just been it 3 times with 3 different variatons of drakes, and still nothing. NO ACHIEV..... 

Please help or fix it!!! 
ty :)
