### ISSUE TITLE
Therazane's Mercy

### ISSUE THREAD

**Issue by Blindriver38** [gamefreedomgit/Maelstrom#6246]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
Trying to Finish Therazane's Mercy, I can kill all but High Priestess Lorthuna. When I fight her, she runs off, and the quest ssays that you should get progress for her anyways, but nothing happens. I made sure that my Addons are disabled and I still cannot get the quest completion

Character name: Velon
English Client

**How to reproduce:**
Accept the quest, attempt to kill Priestess, watch her run off, no progress given

**How it should work:**
Fight PRiestess Lorthuna, when she gets to a certain point, she should run off and you get teh quest progress completion

**Database links:**
https://www.wowhead.com/quest=26832/therazanes-mercy

**Comment by PanJanuszek** [comment]
Fixed after update

**Comment by Blindriver38** [comment]
Do I need to update my game somehow? I redid the quest and its still not
working

**Comment by Nounnyi** [comment]
I just killed her two times, not letting her get far from me after she jumps. Worked

**Comment by Blindriver38** [comment]
i had to delete the WTF file to get it to work, was a trick a Mod told me
about
