### ISSUE TITLE
Tier 9 Leather sets - Dalaran Vendor

### ISSUE THREAD

**Issue by ETatskyi** [gamefreedomgit/Maelstrom#6294]
**Description:**
Tier 9 does not sold by Leather Gear Vendor in Dalaran - https://www.wowhead.com/cata/npc=35497/rafael-langrom

**How to reproduce:**
Speak with Vendor - there is no T9 set items

**How it should work:**
https://www.wowhead.com/cata/npc=35497/rafael-langrom should sell T9 set items

**Database links:**

**Comment by ETatskyi** [comment]
Same situation with mail vendor

**Comment by ETatskyi** [comment]
its about Cata, haven't check on WotLK

**Comment by Afgann** [comment]
fixed

**Comment by ETatskyi** [comment]
Leather vendor fixed, but the neighbor mail vendor still not selling t9 set

**Comment by Afgann** [comment]
fixed
