### ISSUE TITLE
(Quest) Mor'Shan Caravan Delivery

### ISSUE THREAD

**Issue by Emarcee-Q-Em** [gamefreedomgit/Maelstrom#6318]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**The Mor'Shan Caravan Delivery Quest is bugged.**

**Speaking to the quest NPC does spawn the Master Caravan Kodo, but it does not proceed. This causes a soft-lock and forces the player to relog.**

**The Kodo should proceed along the route until it reaches the Mor'Shan Rampart. Along the way, the player is required to use the shotgun abilities against Burning Blade attackers**

**https://www.wowhead.com/quest=29111/morshan-caravan-delivery**

**Comment by Afgann** [comment]
fixed

**Comment by Emarcee-Q-Em** [comment]
The kodo is still not moving when mounted.
![image](https://github.com/user-attachments/assets/b501419c-6600-4543-af6d-9e33eeae9e2a)
