### ISSUE TITLE
Declawing doomclaw bug

### ISSUE THREAD

**Issue by Beeeefsquatch** [gamefreedomgit/Maelstrom#6335]
[//]: # (REMBEMBER! Add links to things related to the bug using for example:)
[//]: # (https://www.wowhead.com/cata)

**Description:**
The quest Declawing Doomclaw seems to be bugged and I cannot complete the quest

**How to reproduce:**

After I have the quest item I cannot turn it in
**How it should work:**
The quest item should be able to be turned in and then you get to choose the reward

**Database links:**
N/a talked with GM in-game

**Comment by Afgann** [comment]
Can you check if quest is completeable now? Should be fixed.

**Comment by Beeeefsquatch** [comment]
I still cannot accept quest after I abandoned it to try and re accept it. I still have the quest item in my inventory

**Comment by Afgann** [comment]
> I still cannot accept quest after I abandoned it to try and re accept it. I still have the quest item in my inventory

Sorry, fix wasn't applied properly, could you check again?

**Comment by Beeeefsquatch** [comment]
Still nothing
