### ISSUE TITLE
Trial of the Naaru: Magtheridon

### ISSUE THREAD

**Issue by Rampageris** [gamefreedomgit/Maelstrom#6794]
[Trial of the Naaru: Magtheridon]
https://www.wowhead.com/cata/quest=10888/trial-of-the-naaru-magtheridon
I kill boss and i can't submit the quest.

**Comment by Afgann** [comment]
fixed

**Comment by Rampageris** [comment]
<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/7e25c6ee-1a1f-45da-b013-cd3560562c0b" />
dont work again

**Comment by leonovpavel035-source** [comment]
https://www.youtube.com/watch?v=rwsvKOhZHvQ HERE IS THE PROOF ITS NOT FIXED. DO SOMETHING PLS
